# Generated by Django 2.2.6 on 2021-06-01 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubinfo',
            name='name',
            field=models.CharField(max_length=20, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='deliveried',
            name='final',
            field=models.IntegerField(choices=[(1, '进行中'), (3, '淘汰'), (2, '通过')], verbose_name='final'),
        ),
    ]
