# Generated by Django 2.2.6 on 2021-06-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_auto_20210601_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubinfo',
            name='adminid',
            field=models.IntegerField(default=1, unique=True),
        ),
        migrations.AlterField(
            model_name='deliveried',
            name='final',
            field=models.IntegerField(choices=[(3, '淘汰'), (2, '通过'), (1, '进行中')], verbose_name='final'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='gender',
            field=models.IntegerField(choices=[(1, '男'), (2, '女')], verbose_name='gender'),
        ),
    ]
