# Generated by Django 2.2.6 on 2021-06-01 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_auto_20210601_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubinfo',
            name='adminid',
        ),
        migrations.AlterField(
            model_name='deliveried',
            name='final',
            field=models.IntegerField(choices=[(3, '淘汰'), (2, '通过'), (1, '进行中')], verbose_name='final'),
        ),
    ]
