# Generated by Django 2.2.6 on 2021-06-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0007_clubinfo_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubinfo',
            name='admin',
            field=models.CharField(max_length=10, unique=True, verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='deliveried',
            name='final',
            field=models.IntegerField(choices=[(1, '进行中'), (2, '通过'), (3, '淘汰')], verbose_name='final'),
        ),
    ]
