# Generated by Django 2.2.6 on 2021-06-02 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0009_auto_20210602_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubadmin',
            name='depart',
            field=models.CharField(default=None, max_length=10, verbose_name='depart'),
        ),
        migrations.AlterField(
            model_name='deliveried',
            name='final',
            field=models.IntegerField(choices=[(2, '通过'), (3, '淘汰'), (1, '进行中')], verbose_name='final'),
        ),
    ]
